version: '3'
services:
  muon_api:
    container_name: muon-node
    restart: always
    network_mode: host
    build:
      context: .

    depends_on:
      - muon_mongo
      - muon_redis

  muon_mongo:
    network_mode: host
    container_name: mongo
    image: mongo
    command: mongod --bind_ip 127.0.0.1

  muon_redis:
    network_mode: host
    container_name: redis
    image: redis:6
    command: redis-server --bind 127.0.0.1
